### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by bentley**
None of these are typos, but they stuck out to me when reading. Are the changes on base?

### CODE REVIEW

**Comment by bentley** [comment]
Ah, I see `content.opf` says `en-GB`. Feel free to drop commits that aren’t desired.

**Comment by acabal** [comment]
These look good, but can you edit the commit messages so that they are prefaced by `[Editorial]`, and drop the two Americanization commits? Then I can merge this in. Thanks!

**Comment by bentley** [comment]
Done.

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
